Repository Rikelmelopes/FrontEnd_API-Deputados, pull requests merged in 2023-05, with the labels that each got.

#17 Create LICENSE
  LICENSE
Labels: documentation

#20 tela de loading concluida com direcionamento para deputados e correcao…
  components/Pagina.jsx
  package-lock.json
  package.json
  pages/deputados.jsx
  pages/index.jsx
Labels: bug, enhancement

#31 Estilisa
  components/Pagina.jsx
  pages/deputados/index.jsx
Labels: enhancement
